# Generated by Django 4.0.3 on 2022-03-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='colg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stud_name', models.CharField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Qualification', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('DOB', models.DateField()),
            ],
        ),
    ]
